### ISSUE TITLE
Plugin not getting fabric switch ips

### ISSUE THREAD

**Issue by gollumsss** [rc9000/nd2-worker-plugin-aci#1]
Hi,

great plugin but in our infrastructure it is is not working ok as I get these messages (-D option used on macsuck):
...
cisco aci macsuck - F8:72:EA:66:F2:8D fabric switch 0.0.0.0 port Ethernet1/2 is unknown to netdisco, skipped
...
I can also see that this is due to plugin/netdisco¿? not getting devips of the fabric switches:
...
NetdiscoX::Util::ACI mac_arp_info - pod 1 node 123 port eth1/2 mac F8:72:EA:66:F2:8D vlan 41 arpip 10.105.240.8 devname LRF-B-R03-1 devip 0.0.0.0
...
Maybe we miss some configuration or something has changed in Version 4.2(7f)??? 

If you need more detailed debugging information or us doing some specific tests just ask.

Congrats for the plugin again.

**Comment by rc9000** [comment]
Hi & thanks, glad you like it :) I actually didn't look at this code in quite a while, but I just tried with the APIC version we have now (4.3(3l)) and I'm still getting the switch IPs as expected in the devip field. 

This is read from here:

    https://<apic>/api/node/class/topSystem.json
        {'topSystem'}->{attributes}->[<array, system index>]->{oobMgmtAddr}

Are your oobMgmtAddr 0.0.0.0 in there? Maybe you have inbMgmtAddr instead? 

You can get the JSON file by running e.g.
    NETDISCOX_DUMPJSON=1  netdisco-do -D -d ...  arpnip

then it will be stored as `/tmp/https(url-encoded-hostname)topSystem.json`

**Comment by gollumsss** [comment]
I checked and you were right, we have in the json dumps:

"oobMgmtAddr" : "0.0.0.0" (I understand this equals "not defined",)
and
"inbMgmtAddr" : "XX.XXX.X.XXX" (the correct IP of the fabric switch)

So the answer is that we have define oobMgmtAddr in each fabric switch with the data of inbMgmtAddr ... right? I do not know what implies in terms of risk or downtime, I will have to check with our support.

One last question, why use oobMgmt and not inbMgmt? Our fabric is doing great in production but maybe this implies something that we missed when it was configured or can arise problems in the future.

Thank you again for your time.

**Comment by rc9000** [comment]
Wait don't change anything on your end, I'll adapt the code so it can either use oobMgmtAddr or inbMgmtAddr - it just happened that our fabrics always had a oobMgmtAddr defined.

**Comment by gollumsss** [comment]
Ok then, I'll wait to test the new code.
Thank you again for your time.

**Comment by rc9000** [comment]
Ok it should be reading inbMgmtAddr now if there is no oobMgmtAddr. I can not test it very well since we only seem to have oob everywhere, but I hope it works for you.

**Comment by gollumsss** [comment]
I've just tried and seems to work OK, now says it is storing entries. After that I can find them via the netdisco web searching MACs & IPs.
Many thanks for the fixing!!!
