### ISSUE TITLE
APIC 5.2(8h) support

### ISSUE THREAD

**Issue by lucdnb** [rc9000/nd2-worker-plugin-aci#10]
Hello dear developer!
First of all, I have to say that this plugin is awesome, thanks for your contribuition!

I need to integrate Netdisco with my ACI environment that is in 5.2(8h) version.
I've follow the entire procedure and after running the command to discover the APIC, I have the this certificate error message:

> ~/bin/netdisco-do discover -d x.x.x.x
> [6809] 2024-08-20 17:03:10  info App::Netdisco version 2.076005 loaded.
> [6809] 2024-08-20 17:03:10  info discover: [x.x.x.x] started at Tue Aug 20 14:03:10 2024
> Unknown charname 'RIGHTWARDS BLACK ARROW' at /home/netdisco/perl5/lib/perl5/App/Netdisco/Worker/Plugin.pm line 40.
> [6809] 2024-08-20 17:03:10  info  [10.238.181.1] NetdiscoX::Properties found an ACIController - running device.layers fixup
> [6809] 2024-08-20 17:03:10  info  [10.238.181.1] NetdiscoX::FabricDevices - updating custom_fields for devices managed by this APIC
> [6809] 2024-08-20 17:03:10 error  [10.238.181.1] NetdiscoX::Util::ACI - http 500 reply Can't connect to x.x.x.x:443 (certificate verify failed)
> 
> SSL connect attempt failed error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed at /home/netdisco/perl5/lib/perl5/LWP/Protocol/http.pm line 49.
> Use of uninitialized value in concatenation (.) or string at /home/netdisco/nd2-worker-plugin-aci/lib/App/NetdiscoX/Util/ACI.pm line 303.
> [6809] 2024-08-20 17:03:11  info discover: finished at Tue Aug 20 14:03:11 2024
> [6809] 2024-08-20 17:03:11  info discover: status info: skip: driver or action not applicable

Can you help me about this issue? Maybe I need to make some changes regarding my APIC version?

Many thanks!

**Comment by rc9000** [comment]
Hi! This is unrelated to the APIC version so far, your Perl does not talk to the APIC at all due to the certificate issue. You might need to set the hostname that is expected for the certificate in `device_auth.https_hostname`, or worst case you can also skip TLS verification with  `PERL_LWP_SSL_VERIFY_HOSTNAME=0`. There some more details in the https://github.com/rc9000/nd2-worker-plugin-aci/blob/master/README.md

Good luck!

**Comment by lucdnb** [comment]
Hi!
Yes this issue is about my APIC https certificate.
I have a problem: my certificate do not have "hostname" or "host" field...

![image](https://github.com/user-attachments/assets/760f0482-f3c5-47eb-b885-f078228f2f6c)

Skipping the verification by running `PERL_LWP_SSL_VERIFY_HOSTNAME=0` or `export PERL_LWP_SSL_VERIFY_HOSTNAME=0` doesnt work. I keeping receiving the certificate error (500).

There is other way to solve this issue? Can I disable the ssl verification for this case?

Thanks.

**Comment by rc9000** [comment]
I made a new version that can also take `PERL_LWP_SSL_VERIFY_MODE=0` which should completely skip checking the certificate. Can you replace the `lib/App/NetdiscoX/Util/ACI.pm` file and try like this:

    PERL_LWP_SSL_VERIFY_HOSTNAME=0 PERL_LWP_SSL_VERIFY_MODE=0 netdisco-do  arpnip -D -d apic.weyland-yutani.co.jp

**Comment by lucdnb** [comment]
Great! It works!
But, the discover now need to be done by exactly this command. So, Netdisco are not able to done the correct discover, macsuck and arpnip on APIC devices, right?

To do so, one of my options is use crontab to run these commands some times for day.

Do you see other way to achieve it? Maybe some change in Netdisco.

**Comment by lucdnb** [comment]
Other thing, new leafs is not taking the correct parameters. So its not taking macsuck and discover correctly.
Do you know why this problem?


- New Leafs is not taking this fields:
![image](https://github.com/user-attachments/assets/2a9a6146-3812-462f-9f4d-2de1afb71f29)


- Leafs added days before this changes in plugin and working (showing all mac and IP information):
![image](https://github.com/user-attachments/assets/335c08f8-0ce0-45cb-8a4e-56557d167b63)

**Comment by rc9000** [comment]
You can put these variables either in the systemd service or docker-compose file you use to start netdisco.

* https://serverfault.com/questions/413397/how-to-set-environment-variable-in-systemd-service
* https://docs.docker.com/compose/environment-variables/set-environment-variables/

**Comment by lucdnb** [comment]
Great! Thank you for all responses.
