### ISSUE TITLE
MACs not learned from APIC

### ISSUE THREAD

**Issue by Mike2912** [rc9000/nd2-worker-plugin-aci#7]
Hi,

I installed this plugin and I can see ACI Switches and Controller in Netdisco. Also the custom fields are filled with correct information.
But I can't see the MAC-Adresses of connected devices in Netdisco.
I'm facing two problems I think.
First of all, if Unicast-Routing (L3) is inactive for a Bridge Domain, Learned MACs do not appear in any way (not in netdisco, nor in a macsuck-log) 
If Unicast Routing is acitve, I can see the MAC in macsuck output:
`debug  [apic] cisco aci macsuck - xx:xx:xx:24:B8:2E fabric switch xxx.xxx.xxx.xxx port Ethernet1/5 is an uplink, skipped`
If I check the database, every connected Leaf-Port is marked as uplink.
In this case, there is the setting `aci_ignore_uplink_re`.

Can someone give me an example value for this setting? I would like to mark only remote_types starting with "topology" as uplinks.

Thanks in advance.

**Comment by rc9000** [comment]
Hi ! Regarding `aci_ignore_uplink_re`, you can look at the values you have in the db with this query, e.g.

    netdisco@vmnd812p01:~> netdisco-do psql
    netdisco=> select ip, port, remote_type from device_port where ip =  '10.219.2.76' and remote_type is not null order by port;
    
         ip      |      port       |                          remote_type
    -------------+-----------------+----------------------------------------------------------------
     10.219.2.76 | Ethernet1/2     | NetApp HCI H410S-1 Storage Node, Release Element Software 12.7
     10.219.2.76 | Ethernet1/51    | topology/pod-1/node-101
     10.219.2.76 | Ethernet1/52    | topology/pod-1/node-102
     10.219.2.76 | Ethernet103/1/6 | NetApp HCI H410S-1 Storage Node, Release Element Software 12.7

So just setting the value to `^topology` or even `topology` might do what you want. For multiple values, you can use e.g. `(NetApp|topology)`.

For the "Unicast-Routing (L3) is inactive" case, this probably means that the MACs do not appear in the `{fvCEp}->{children}->{fvRsCEpToPathEp}` structure of the APIC API. Is there a place in the Object browser or URL in moquery where you see the MACs that you'd expect to be in Netdisco for the port? Then we could maybe try to query this location as well.

**Comment by Mike2912** [comment]
Hi,
thanks for quick response. 

I tried this already, I put a line `aci_ignore_uplink_re: '^topology'` at the end of my deployment.yml and restarted the netdisco-daemon.
remote_type definitely doesn't start with topology:
```
netdisco=> select ip, port, is_uplink, remote_type from device_port where ip = '172.31.252.225' and port = 'Ethernet1/5';
       ip       |    port     | is_uplink |                                remote_type
----------------+-------------+-----------+--------------------------------------------
 172.31.252.225 | Ethernet1/5 | t         | Debian GNU/Linux 10 (buster) Linux ...
(1 row)

netdisco=>
```
But I still get this debug output from Macsuck:
`[17669] 2023-12-11 14:26:05 debug  [172.31.255.61] cisco aci macsuck - 90:1B:0E:24:B8:66 fabric switch 172.31.252.225 port Ethernet1/5 is an uplink, skipped`

It looks like I didn't set the variable correctly.

For the second case (L3), I can not reproduce problem right now. The MACs appear in the API structure and in debug output.

**Comment by rc9000** [comment]
Oh I misread what you want, to mark everything but "topology" I hope this negative lookahead will work:

    aci_ignore_uplink_re: "^(?!topology)"

**Comment by Mike2912** [comment]
That doesn't work.
I tried something and found out, that "Debian" (to test positiv matching) works fine, but if I add any special character, for examle "^Debian" or "(Debian)" it doesn't match anymore. 

Does this work for you?

**Comment by Mike2912** [comment]
found the reason: 
in [Nodes.pm](https://github.com/rc9000/nd2-worker-plugin-aci/tree/master/lib/App/NetdiscoX/Worker/Plugin/Macsuck/Nodes.pm) on Line 91 is the \Q infront of the variable:
`... !~ m/\Q$aci_ignore_uplink_re/){`
This doesn't work in regex. If you put it at the end, everything is fine. 
Also the negative lookahead `aci_ignore_uplink_re: "^(?!topology).*$"` is working :)

**Comment by rc9000** [comment]
thanks for figuring that out, I must have added the \Q once because I thought it would help... well it clearly.didn't so far :)  So I just removed it and also added the examples from here to the readme.
